-- FINALIZED as memorybox/migrations/039_p2_i14_voice_requires_prepared_text.sql
-- This copy remains only as the reviewed proposal pointer. Apply the
-- migrations/ file through python -m memorybox migrate, never this docs copy.
